version: '3.4'

services:
  openhomeenergymanager.blazor:
    image: ${DOCKER_REGISTRY-}openhomeenergymanagerblazor
    build:
      context: .
      dockerfile: OpenHomeEnergyManager.Blazor/Dockerfile

  openhomeenergymanager.api:
    image: ${DOCKER_REGISTRY-}openhomeenergymanagerapi
    network_mode: "host"
    build:
      context: .
      dockerfile: OpenHomeEnergyManager.Api/Dockerfile
    volumes:
        - data:/app/data

volumes:
    data:
