version: '3.4'

services:
  openhomeenergymanager.blazor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=http://+:5124
    ports:
      - "5001:80"

  openhomeenergymanager.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5123
    #ports:
    #  - "5001:80"
    #  - "9522:9522/udp"
